name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/ASDML.NET
    - name: Build
      run: dotnet build src/ASDML.NET -c Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - name: Test
      run: dotnet test src/ASDML.NET -c Release --no-restore -v normal
