name: NuGet Push

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/ASDML.NET/ASDML.NET/ASDML.NET.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
