name: NuGet Push

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/ASDML.NET
    - name: Build
      run: dotnet build src/ASDML.NET -c Release --no-restore
    - name: Pack
      run: dotnet pack src/ASDML.NET/ASDML.NET -c Release -p:SourceRevisionId=$(git rev-parse --short HEAD) -o . --no-build
    - name: Push
      run: dotnet nuget push -s https://nuget.org -k ${{secrets.NUGET_API_KEY}} --skip-duplicate *.nupkg
